"""
Global constants for RETRACK - RailSync-AI system
"""

# Departments
DEPT_CIVIL = "CIVIL"
DEPT_ELECTRICAL = "ELECTRICAL"
DEPT_SIGNAL_TELECOM = "SIGNAL_TELECOM"

ALL_DEPARTMENTS = [DEPT_CIVIL, DEPT_ELECTRICAL, DEPT_SIGNAL_TELECOM]

# Maintenance Request Priorities
PRIORITY_LOW = "LOW"
PRIORITY_MEDIUM = "MEDIUM"
PRIORITY_HIGH = "HIGH"
PRIORITY_CRITICAL = "CRITICAL"

ALL_PRIORITIES = [PRIORITY_LOW, PRIORITY_MEDIUM, PRIORITY_HIGH, PRIORITY_CRITICAL]

# Maintenance Request Statuses
STATUS_PENDING = "PENDING"
STATUS_VALIDATED = "VALIDATED"
STATUS_BUNDLED = "BUNDLED"
STATUS_SCHEDULED = "SCHEDULED"
STATUS_APPROVED = "APPROVED"
STATUS_IN_PROGRESS = "IN_PROGRESS"
STATUS_COMPLETED = "COMPLETED"
STATUS_REJECTED = "REJECTED"
STATUS_CANCELLED = "CANCELLED"

# Train Types
TRAIN_EXPRESS = "EXPRESS"
TRAIN_PASSENGER = "PASSENGER"
TRAIN_FREIGHT = "FREIGHT"
TRAIN_SPECIAL = "SPECIAL"

# User Roles
ROLE_ADMIN = "ADMIN"
ROLE_CONTROLLER = "CONTROLLER"
ROLE_STATION_MASTER = "STATION_MASTER"
ROLE_ENGINEER = "ENGINEER"
ROLE_FIELD_OFFICER = "FIELD_OFFICER"
ROLE_VIEWER = "VIEWER"

# Spatial Bundling Parameters
MAX_BUNDLING_DISTANCE_KM = 5.0

# System info
APP_TITLE = "RETRACK - RailSync-AI API"
APP_VERSION = "1.0.0"
SIH_PROBLEM_STATEMENT_ID = "26027"
